name: Check linters
on: 
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: urnai/linter
    steps:
      - name: Run lint
#        uses: actions/checkout@v3
        run: sudo apt-get update && sudo apt-get install make && make lint
#        run: make lint
      


# name: Check linters
# on:
#   push:
#     branches: ["master"]
#   pull_request:
#     branches: ["master"]

# jobs:
#   container-test-job:
#     runs-on: ubuntu-latest
#     container: urnai/linter
#     steps:
#       - name: Run lint
#         uses: actions/checkout@v3
#         ##run: make lint

# ---
# name: Run tests
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# jobs:
#   test:
#     name: Run unit tests
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - run: make build
#       - run: make test-coverage